### ISSUE TITLE
flyin plugin option flyin_direction=x not working after restarting the desktop.

### ISSUE THREAD

**Issue by Techman35** [compiz-reloaded/compiz#38]
when using flyin_direction=x option in flyin plugin it work until restart or simply by logout login... the flyin plugin stop working. and say N/A in compizmanger settings.

![screenshot50](https://cloud.githubusercontent.com/assets/14001966/17958652/f0bac8ae-6a8a-11e6-9aee-359f3e722dde.png)
![screenshot51](https://cloud.githubusercontent.com/assets/14001966/17958653/f0c0d28a-6a8a-11e6-9636-f9afd38edf38.png)

**Comment by ethus3h** [comment]
This was fixed a few hours earlier, I think… https://github.com/compiz-reloaded/compiz-plugins-main/commit/269a6d05d18dcda7fd38b4971c831f306aa6b7ed

**Comment by soreau** [comment]
@ethus3h That patch doesn't fix this problem. @Techman35 If you wait for a few seconds after starting ccsm, do the options appear?

**Comment by Techman35** [comment]
yes.... i have to wait a few second.. and it appear but i have to  set the option flyin_direction=x  to make it work again

**Comment by soreau** [comment]
The patch that @ethus3h mentioned should fix that problem, have you updated plugins-main to latest?

**Comment by Techman35** [comment]
Ok i will try the patch now.... and i will let you know :)

**Comment by soreau** [comment]
Yes, it should be installed with compiz-fusion-plugins-main-git. To be clear, 'N/A' appears when navigating to animation options in ccsm before the other animation plugins are loaded. This isn't a bug and doesn't cause a problem. The patch should fix flyin_direction option. If not, try 'reset to defaults' in ccsm>preferences and reconfigure ccsm.

**Comment by Techman35** [comment]
@soreau  YES!!!!!!! it works  :D
Resetting the ccsm to default and reconfiguring the animations did the trick  THANKS YOU GUYS :)

**Comment by Techman35** [comment]
@soreau  YES!!!!!!! it works  :D
Resetting the ccsm to default and reconfiguring the animations did the trick  THANKS YOU GUYS :)
